-- CC resolves relative require() patterns against the directory of the running
-- program, so from /pod/ the module "pod.config" is searched for at
-- /pod/pod/config.lua and never found. Patterns beginning with "/" are exempt
-- from that combine, so rooting the search path at / makes "pod.x" resolve to
-- /pod/x.lua no matter where the program was launched from.
package.path = "/?.lua;/?/init.lua;" .. package.path

local config = require("pod.config")

local names = {}
local others = {}
for _, name in ipairs(peripheral.getNames()) do
    if peripheral.hasType(name, "ion_thruster") then
        names[#names + 1] = name
    else
        others[#others + 1] = name
    end
end
table.sort(names)
table.sort(others)

term.clear()
term.setCursorPos(1, 1)
print("ION THRUSTER DISCOVERY")
print("Computer ID: " .. tostring(os.getComputerID()))
print("Corner: " .. tostring(config.corner))
print("Found: " .. tostring(#names))
print("Expected: " .. tostring(config.expectedThrusterCount))
print("")

for index, name in ipairs(names) do
    print(string.format("%02d  %s", index, name))
end

local file = assert(fs.open(config.manifestPath, "w"))
file.writeLine("-- Generated by /pod/discover.lua. Review before approval.")
file.writeLine("return {")
for _, name in ipairs(names) do
    file.writeLine("    " .. string.format("%q", name) .. ",")
end
file.writeLine("}")
file.close()

-- Everything that is not a thruster, so the Rotation Speed Controller and prop
-- bearing names can be copied straight into propController / propBearing.
-- Written to disk as well as printed: the screen scrolls, and these names are
-- the ones most likely to need reading back later.
local reportPath = config.deviceReportPath or "/pod/device_report.txt"

local report = {
    "POD DEVICE REPORT",
    "Computer ID: " .. tostring(os.getComputerID()),
    "Corner: " .. tostring(config.corner),
    "Generated UTC ms: " .. tostring(os.epoch("utc")),
    "",
    "ION THRUSTERS (" .. #names .. " found, " .. config.expectedThrusterCount .. " expected)",
}
for index, name in ipairs(names) do
    report[#report + 1] = string.format("  %02d  %s", index, name)
end

report[#report + 1] = ""
report[#report + 1] = "OTHER DEVICES (prop candidates)"

print("")
print("OTHER DEVICES (prop candidates):")
if #others == 0 then
    print("  none")
    report[#report + 1] = "  none"
end
for _, name in ipairs(others) do
    local line = "  " .. name .. "  [" .. tostring(peripheral.getType(name)) .. "]"
    print(line)
    report[#report + 1] = line

    local methodsOk, methods = pcall(peripheral.getMethods, name)
    if methodsOk and methods then
        table.sort(methods)
        report[#report + 1] = "        methods: " .. table.concat(methods, ", ")
    end
end

local reportFile = assert(fs.open(reportPath, "w"))
reportFile.write(table.concat(report, "\n"))
reportFile.close()

print("")
print("Saved: " .. config.manifestPath)
print("Saved: " .. reportPath)
if #names ~= config.expectedThrusterCount then
    printError("COUNT MISMATCH: do not approve this manifest")
else
    print("Review the list, then set manifestApproved = true")
end
